NebbAir/Models/ErrorViewModel.cs
using System;

namespace NebbAir.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NebbAir/Models/Patnici.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace NebbAir.Models
{



    public class Patnici
    {
        [Key]
        public int PatnikID { get; set; }
        [Required]
        [Display(Name = "First Name")]
        public string Ime { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string Prezime { get; set; }

        [Required]
        [Display(Name = "Birth Date")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        public DateTime DataNaRagjanje { get; set; }

        [Required]
        [Display(Name = "Passport Number")]
        public string PassporNo { get; set; }

        [Required]
        [Display(Name = "Flight Number")]
        public string FlightNo { get; set; }

        [Required]
        [Display(Name = "Origin")]
        public string Origin { get; set; }

        [Required]
        [Display(Name = "Destination")]
        public string Destination { get; set; }

        [Required]
        [Display(Name = "Departure")]
        public DateTime Departure { get; set; }

        [Display(Name = "Return")]
        public DateTime Return { get; set; }

        [Required]
        [Display(Name = "Carry On")]
        public int CarryOn { get; set; }

        [Required]
        [Display(Name = "Trolley")]
        public int Trolley { get; set; }

        [Required]
        [Display(Name = "Check In")]
        public int CheckIn { get; set; }
    }
}

NebbAir/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using NebbAir.Models;

namespace NebbAir.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NebbAir/Controllers/PatnicisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NebbAir.Data;
using NebbAir.Models;

namespace NebbAir.Controllers
{
    public class PatnicisController : Controller
    {
        private readonly NebbAirContext _context;

        public PatnicisController(NebbAirContext context)
        {
            _context = context;
        }

        // GET: Patnicis
        public async Task<IActionResult> Index()
        {
            return View(await _context.Patnici.ToListAsync());
        }

        // GET: Patnicis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patnici = await _context.Patnici
                .FirstOrDefaultAsync(m => m.PatnikID == id);
            if (patnici == null)
            {
                return NotFound();
            }

            return View(patnici);
        }

        // GET: Patnicis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Patnicis/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("PatnikID,Ime,Prezime,DataNaRagjanje,PassporNo,FlightNo,Origin,Destination,Departure,Return,CarryOn,Trolley,CheckIn")] Patnici patnici)
        {
            if (ModelState.IsValid)
            {
                _context.Add(patnici);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(patnici);
        }

        // GET: Patnicis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patnici = await _context.Patnici.FindAsync(id);
            if (patnici == null)
            {
                return NotFound();
            }
            return View(patnici);
        }

        // POST: Patnicis/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("PatnikID,Ime,Prezime,DataNaRagjanje,PassporNo,FlightNo,Origin,Destination,Departure,Return,CarryOn,Trolley,CheckIn")] Patnici patnici)
        {
            if (id != patnici.PatnikID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patnici);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatniciExists(patnici.PatnikID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patnici);
        }

        // GET: Patnicis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patnici = await _context.Patnici
                .FirstOrDefaultAsync(m => m.PatnikID == id);
            if (patnici == null)
            {
                return NotFound();
            }

            return View(patnici);
        }

        // POST: Patnicis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patnici = await _context.Patnici.FindAsync(id);
            _context.Patnici.Remove(patnici);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatniciExists(int id)
        {
            return _context.Patnici.Any(e => e.PatnikID == id);
        }

       
        [Route("~/Patnicis/GetPasos/{pasos}")]
        public async  Task<Patnici> GetPasos(string pasos)
        {
           

            var patnici =await  _context.Patnici
                .FirstOrDefaultAsync(m => m.PassporNo == pasos);

            return   patnici;
        }


        [Route("~/Patnicis/GetFlight/{flightNo}")]
        public async Task<Patnici> GetFlight(string flightNo)
        {


            var patnici = await _context.Patnici
                .FirstOrDefaultAsync(m => m.FlightNo == flightNo);

            return patnici;
        }



















        //[HttpGet]
        //public I GetFlight(string flightNo)
        //{


        //    var patnici = _context.Patnici
        //        .FirstOrDefaultAsync(m => m.FlightNo == flightNo);

        //    return Json(patnici);
        //}
    }

    
}

NebbAir/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <div class="row home-page-links">
        <div class="col-md-6 link-1">
            <a asp-area="" asp-controller="Patnicis" asp-action="Create">
                <h4><i class="fa fa-plane"></i> Book a New Flight </h4>
            </a>
        </div>
        <div class="col-md-6 link-2">
            <a asp-area="" asp-controller="Patnicis" asp-action="Index">
                <h4><i class="fa fa-address-card"></i> View All booked Flights </h4>
            </a>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <img src="~/img/logo.png" class="logo" />
        </div>
    </div>
</div>

NebbAir/Views/Patnicis/Create.cshtml
@model NebbAir.Models.Patnici

@{
    ViewData["Title"] = "Create";
}

<h3>Book a New Flight</h3>
<p>
    Here you can book a new flight <br />
    <em>The fields marked with <span style="color: red;"> * </span> ARE REQUIRED</em>
</p>


<hr />
<div class="row">
    <div class="col-md-8">
        <form asp-action="Create" onsubmit=" return Proverka()">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <h4>Passenger Information:</h4><br />
            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Ime" class="control-label">First Name<span style="color: red;"> * </span></label>
                    <input asp-for="Ime" class="form-control" />
                    <span asp-validation-for="Ime" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="DataNaRagjanje" class="control-label">Birth Date<span style="color: red;"> * </span></label>
                    <input asp-for="DataNaRagjanje" class="form-control" />
                    <span asp-validation-for="DataNaRagjanje" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Prezime" class="control-label">Last Name<span style="color: red;"> * </span></label>
                    <input asp-for="Prezime" class="form-control" />
                    <span asp-validation-for="Prezime" class="text-danger"></span>
                </div>

                <div class="form-group col-sm-6">
                    <label asp-for="PassporNo" class="control-label">Passport Number<span style="color: red;"> * </span></label>
                    <input asp-for="PassporNo" class="form-control" title="Example passport number : A1234567" />
                    <span asp-validation-for="PassporNo" class="text-danger"></span>
                </div>
            </div>
            <hr />

            <h4>Flight Information:</h4>
            <div class="row">
                <div class="col-sm-6">

                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="FlightNo" class="control-label">Flight Number<span style="color: red;"> * </span></label>
                    <input asp-for="FlightNo" class="form-control" title="Input four digit flight number" />
                    <span asp-validation-for="FlightNo" class="text-danger"></span>
                </div>
            </div>

            <div class="row">

                <div class="form-group col-sm-6">
                    <label asp-for="Origin" class="control-label">Departure<span style="color: red;"> * </span></label>
                    <input asp-for="Origin" class="form-control" />
                    <span asp-validation-for="Origin" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Destination" class="control-label">Destination<span style="color: red;"> * </span></label>
                    <input asp-for="Destination" class="form-control" />
                    <span asp-validation-for="Destination" class="text-danger"></span>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-sm-6">
                    <label asp-for="Departure" class="control-label">Departure date<span style="color: red;"> * </span></label>
                    <input asp-for="Departure" class="form-control" />
                    <span asp-validation-for="Departure" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-6">
                    <label asp-for="Return" class="control-label">Return date<span style="color: red;"> * </span></label>
                    <input asp-for="Return" class="form-control" />
                    <span asp-validation-for="Return" class="text-danger"></span>
                </div>
            </div>
            <hr />

            <h4>Luggage:</h4><br />
            <div class="row">

                <div class="form-group col-sm-4">
                    <label asp-for="CarryOn" class="control-label">Carry On</label>
                    <input asp-for="CarryOn" class="form-control" />
                    <span asp-validation-for="CarryOn" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-4">
                    <label asp-for="Trolley" class="control-label">Trolley </label>
                    <input asp-for="Trolley" class="form-control" />
                    <span asp-validation-for="Trolley" class="text-danger"></span>
                </div>
                <div class="form-group col-sm-4">
                    <label asp-for="CheckIn" class="control-label">Check-In Bag</label>
                    <input asp-for="CheckIn" class="form-control" />
                    <span asp-validation-for="CheckIn" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <p><em>Double check the information before you book your flight</em></p>
                <input type="submit" value="Book" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

}

<script>
    //regex broj na pasos
    $(document).ready(function () {
        $("input#PassporNo").on("input", function () {
            var input = document.getElementById("PassporNo").value;
            var regex = new RegExp("^[A-Z0-9]+$")
            if (regex.test(input) && input.length === 8) {
                //console.log("Rabote");
                $("input#PassporNo").css("border-color", "green")
            }
            else {
                //console.log("asd");
                $("input#PassporNo").css("border-color", "red")
            }
            //console.log(regex.test(input));
        })
    })
    //regex broj na let
    $(document).ready(function () {
        $("input#FlightNo").on("input", function () {
            var input = document.getElementById("FlightNo").value;
            var regex = new RegExp("^[0-9]+$")
            if (regex.test(input) && input.length === 4) {
                //console.log("Rabote");
                $("input#FlightNo").css("border-color", "green")
            }
            else {
                //console.log("asd");
                $("input#FlightNo").css("border-color", "red")
            }
            //console.log(regex.test(input));
        })
    })

    $(function () {
        $("input#PassporNo").tooltip();
        $("input#FlightNo").tooltip();
    });
    //function on submit
    function Proverka() {
        
            var passportInput = document.getElementById("PassporNo").value;
            var passportRegex = new RegExp("^[A-Z0-9]+$")
            var flightInput = document.getElementById("FlightNo").value;
            var flightRegex = new RegExp("^[0-9]+$")
            if (passportRegex.test(passportInput) && passportInput.length === 8 && flightRegex.test(flightInput) && input.flightInput === 4) {
                //console.log("Rabote");

                return true
            }
        
            else {
                alert("Passport or Flight Number are incorrect")
                return false
            }

           
    }
         
    //populate passenger information fields
    $(document).ready(function () {
        $("input#PassporNo").on("input", function () {
            var input = document.getElementById("PassporNo").value;
            var regex = new RegExp("^[A-Z0-9]+$")
            if (regex.test(input) && input.length === 8) {

                //$("input#PassporNo").on("input", function () {
                //alert("input - " + input)
                $.ajax({
                    //base address/controller/Action
                    url: '/Patnicis/GetPasos/' + input,
                    type: 'GET',
                    
                    data: null,

                    success: function (result) {
                        //alert(result.ime);
                        $("input#Ime").val(result.ime);
                        $("input#DataNaRagjanje").val(result.dataNaRagjanje);
                        $("input#Prezime").val(result.prezime);

                    },
                    error: function (jqXHR, textStatus, errorThrown, data) {
                        //alert(jqXHR.status);
                        //alert(textStatus);
                        //alert(errorThrown);
                        
                    }
                });
                return false;
            }
        });
    });

    //populate flight information
    //populate passenger information fields
    $(document).ready(function () {
        $("input#FlightNo").on("input", function () {
            var input = document.getElementById("FlightNo").value;
            var regex = new RegExp("^[0-9]+$")
            if (regex.test(input) && input.length === 4) {

                //$("input#PassporNo").on("input", function () {
                //$("input#PassporNo").on("input", function () {
                //alert("input - " + input)
                $.ajax({
                    //base address/controller/Action
                    url: '/Patnicis/GetFlight/' + input,
                    type: 'GET',

                    data: null,

                    success: function (result) {
                        //alert(result.ime);
                        $("input#Origin").val(result.origin);
                        $("input#Destination").val(result.destination);
                        $("input#Departure").val(result.departure);
                        
                        

                    },
                    error: function (jqXHR, textStatus, errorThrown, data) {
                        //alert(jqXHR.status);
                        //alert(textStatus);
//                        alert(errorThrown);

                    }
                });
                return false;
            }
        });
    });
</script>

NebbAir/Views/Patnicis/Delete.cshtml
@model NebbAir.Models.Patnici

@{
    ViewData["Title"] = "Delete";
}

<h3>Delete</h3>

<p>Are you sure you want to delete the flight to <b>@Html.DisplayFor(model => model.Destination) </b>  for the passenger  <b>@Html.DisplayFor(model => model.Ime) @Html.DisplayFor(model => model.Prezime)</b>?</p>
<div>

    <hr />
    <div>

        <hr />
        <dl class="row">
            <div class="col-sm-6">
                <h5>Passenger Information</h5>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Ime)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Ime)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Prezime)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Prezime)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.DataNaRagjanje)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.DataNaRagjanje)
                </dd>
            </div>

            <div class="col-sm-6">
                <h5>Flight Information</h5>
                <dt class="col-sm-8">
                    @Html.DisplayNameFor(model => model.PassporNo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.PassporNo)
                </dd>
                <dt class="col-sm-8">
                    @Html.DisplayNameFor(model => model.FlightNo)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.FlightNo)
                </dd>
                <dt class="col-sm-8">
                    @Html.DisplayNameFor(model => model.Origin)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Origin)
                </dd>
                <dt class="col-sm-8">
                    @Html.DisplayNameFor(model => model.Destination)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Destination)
                </dd>
                <dt class="col-sm-8">
                    @Html.DisplayNameFor(model => model.Departure)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Departure)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Return)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Return)
                </dd>

                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.CarryOn)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CarryOn)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.Trolley)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Trolley)
                </dd>
                <dt class="col-sm-4">
                    @Html.DisplayNameFor(model => model.CheckIn)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.CheckIn)
                </dd>

            </div>
        </dl>
    </div>

    <form asp-action="Delete">
        <input type="hidden" asp-for="PatnikID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to Manifest</a>
    </form>
</div>

NebbAir/Views/Patnicis/Details.cshtml
@model NebbAir.Models.Patnici

@{
    ViewData["Title"] = "Details";
}

<h3>Details</h3>
<p>Full details about the passenger <b>@Html.DisplayFor(model => model.Ime) @Html.DisplayFor(model => model.Prezime)</b>  flight to  <b>@Html.DisplayFor(model => model.Destination)</b></p>
<div class="akcii-details">
    <a asp-action="Index">Back to Manifest</a> |
    <a asp-action="Edit" asp-route-id="@Model.PatnikID">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.PatnikID">Delete</a>
</div>
<div>

    <hr />
    <dl class="row">
        <div class="col-sm-6">
            <h5>Passenger Information</h5>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Ime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ime)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Prezime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Prezime)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.DataNaRagjanje)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.DataNaRagjanje)
            </dd>
        </div>

        <div class="col-sm-6">
            <h5>Flight Information</h5>
            <dt class="col-sm-8">
                @Html.DisplayNameFor(model => model.PassporNo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PassporNo)
            </dd>
            <dt class="col-sm-8">
                @Html.DisplayNameFor(model => model.FlightNo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.FlightNo)
            </dd>
            <dt class="col-sm-8">
                @Html.DisplayNameFor(model => model.Origin)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Origin)
            </dd>
            <dt class="col-sm-8">
                @Html.DisplayNameFor(model => model.Destination)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Destination)
            </dd>
            <dt class="col-sm-8">
                @Html.DisplayNameFor(model => model.Departure)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Departure)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Return)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Return)
            </dd>

            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.CarryOn)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarryOn)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.Trolley)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Trolley)
            </dd>
            <dt class="col-sm-4">
                @Html.DisplayNameFor(model => model.CheckIn)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CheckIn)
            </dd>

        </div>
    </dl>
</div>

NebbAir/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NebbAir</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NebbAir</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Patnicis" asp-action="Index">View All Flights</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Patnicis" asp-action="Create">Book a New Flight</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center ">
            &copy; 2020 - NebbAir - This is a practical project under the mentorship of Nebb and Semos Education | <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> | <a  href="http://nenadristov.azurewebsites.net/">Nenad Ristov</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>